FROM	debian:latest
MAINTAINER Vijo Cherian codervijo@gmail.com

RUN		apt-get -y update && apt-get install -y erlang
RUN		apt-get -y install procps net-tools ssh
#CMD		["lua", "/usr/src/luascope/scope"]
